[project]
name = "ppt-to-video"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "deep-translator>=1.11.4",
    "gtts>=2.5.4",
    "moviepy>=2.2.1",
    "python-pptx>=1.0.2",
    "ruff>=0.13.1",
]
