name: Code Checks

on: [push, pull_request]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Build Documentation
        run: |
          cd docs
          make html
