name: Code Checks

on: [push, pull_request]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run Ruff
        run: ruff .

      - name: Run Ty
        run: ty .

      - name: Run Unit Tests
        run: pytest

      - name: Coverage Report
        run: coverage report -m -fail-under=80

      - name: Build Documentation
        run: |
          cd docs
          make html