name: Code Checks

on: [push, pull_request]

jobs:
  lint:
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -e .[dev]

      - name: Run Ruff
        run: ruff check --fix

      #Disabled type checking for now
      #- name: Run Ty
      #  run: ty check
