name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

      - name: Run Unit Tests
        run: pytest

      - name: Coverage Report
        run: coverage report -m -fail-under=80