name: Testing

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest, windows-latest, macos-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -e .[dev]

      - name: Run Unit Tests
        run: pytest

      - name: Coverage Report
        run: coverage report -m -fail-under=80
